In [1]:
#libraries used
import numpy as np
import laspy 
import matplotlib.pyplot as plt
import open3d as o3d


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
#path set to .LAS File

input_path="../utar/"
output_path="../Converter/"
dataname="UtarMap1"
point_cloud= laspy.read(input_path+dataname+".las")

In [3]:

# Open a file in read mode:
inFile = point_cloud

# Grab a numpy dataset of our clustering dimensions:
dataset = np.vstack([inFile.X, inFile.Y, inFile.Z]).transpose()
colors = np.vstack([inFile.red, inFile.green, inFile.blue]).transpose()

#setting the colors of the pointcloud data to between 1 and 0
colors = colors / 255 / 255
colors = np.round(colors, 1)

print("the ponts")
print(dataset)
print("the colors")
print(colors)



the ponts
[[ 43949208 446099992    144641]
 [ 43949193 446099961    144571]
 [ 43949231 446099986    144586]
 ...
 [ 44013796 446108658    144991]
 [ 44013961 446108645    145009]
 [ 44013982 446108610    145002]]
the colors
[[0.3 0.3 0.3]
 [0.3 0.3 0.3]
 [0.3 0.3 0.3]
 ...
 [0.3 0.3 0.3]
 [0.3 0.3 0.3]
 [0.3 0.3 0.3]]


In [4]:
# Pass xyz and RGB to Open3D.o3d.geometry.PointCloud 

pcd = o3d.geometry.PointCloud()

pcd.points = o3d.utility.Vector3dVector(dataset)

pcd.colors = o3d.utility.Vector3dVector(colors) 


pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))

print (pcd)

print(np.all(np.isfinite(np.asarray(pcd.colors))))


PointCloud with 12613322 points.
True


In [5]:
#Creating the Triangles and Vertices For a Mesh.
mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting (pcd, o3d.utility.DoubleVector([1,2,3,4]))




print("The Vertices")
print(np.asarray(mesh.vertices))
print("The Triangles")
print(np.asarray(mesh.triangles))
print("The Colors")
print(np.asarray(pcd.colors))
print("The Points")
print(np.asarray(pcd.points))

mesh = o3d.geometry.TriangleMesh.compute_triangle_normals (mesh)

The Vertices
[[4.39492080e+07 4.46099992e+08 1.44641000e+05]
 [4.39491930e+07 4.46099961e+08 1.44571000e+05]
 [4.39492310e+07 4.46099986e+08 1.44586000e+05]
 ...
 [4.40137960e+07 4.46108658e+08 1.44991000e+05]
 [4.40139610e+07 4.46108645e+08 1.45009000e+05]
 [4.40139820e+07 4.46108610e+08 1.45002000e+05]]
The Triangles
[[  712845  6323926  5133856]
 [ 2262346  3903491  6776735]
 [10676588 11862652 12241339]]
The Colors
[[0.3 0.3 0.3]
 [0.3 0.3 0.3]
 [0.3 0.3 0.3]
 ...
 [0.3 0.3 0.3]
 [0.3 0.3 0.3]
 [0.3 0.3 0.3]]
The Points
[[4.39492080e+07 4.46099992e+08 1.44641000e+05]
 [4.39491930e+07 4.46099961e+08 1.44571000e+05]
 [4.39492310e+07 4.46099986e+08 1.44586000e+05]
 ...
 [4.40137960e+07 4.46108658e+08 1.44991000e+05]
 [4.40139610e+07 4.46108645e+08 1.45009000e+05]
 [4.40139820e+07 4.46108610e+08 1.45002000e+05]]


In [6]:
#Shaping the quality of the mesh (Rendering)

mesh = mesh.filter_sharpen(number_of_iterations=1, strength=0.010)

In [7]:
#write .LAS file of PCD or PLY or PTS OR XYZRGB

o3d.io.write_point_cloud("../utar/test.ply", pcd, write_ascii=False)

True

In [8]:
#Reading file of PCD or PLY or PTS OR XYZRGB

testing = o3d.io.read_point_cloud("../utar/test.ply")
print(np.asarray(testing.points))
print(np.asarray(testing.colors))


[[4.39492080e+07 4.46099992e+08 1.44641000e+05]
 [4.39491930e+07 4.46099961e+08 1.44571000e+05]
 [4.39492310e+07 4.46099986e+08 1.44586000e+05]
 ...
 [4.40137960e+07 4.46108658e+08 1.44991000e+05]
 [4.40139610e+07 4.46108645e+08 1.45009000e+05]
 [4.40139820e+07 4.46108610e+08 1.45002000e+05]]
[[0.30196078 0.30196078 0.30196078]
 [0.30196078 0.30196078 0.30196078]
 [0.30196078 0.30196078 0.30196078]
 ...
 [0.30196078 0.30196078 0.30196078]
 [0.30196078 0.30196078 0.30196078]
 [0.30196078 0.30196078 0.30196078]]


In [9]:
#writing the .LAS to a mesh.
o3d.io.write_triangle_mesh("../utar/meshes.ply", mesh)

True

In [10]:
#Reading the Mesh
testing = o3d.io.read_point_cloud("../utar/meshes.ply")
print(np.asarray(testing.points))
print(np.asarray(testing.colors))

[[4.39492080e+07 4.46099992e+08 1.44641000e+05]
 [4.39491930e+07 4.46099961e+08 1.44571000e+05]
 [4.39492310e+07 4.46099986e+08 1.44586000e+05]
 ...
 [4.40137960e+07 4.46108658e+08 1.44991000e+05]
 [4.40139610e+07 4.46108645e+08 1.45009000e+05]
 [4.40139820e+07 4.46108610e+08 1.45002000e+05]]
[[0.30196078 0.30196078 0.30196078]
 [0.30196078 0.30196078 0.30196078]
 [0.30196078 0.30196078 0.30196078]
 ...
 [0.30196078 0.30196078 0.30196078]
 [0.30196078 0.30196078 0.30196078]
 [0.30196078 0.30196078 0.30196078]]
